[build]
  command = "npm run build"
  publish = "out"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./package-lock.json"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --no-audit --no-fund"
  CI = "false"
  NEXT_PUBLIC_SITE_URL = "https://bueiro3369.netlify.app"
  GIT_TERMINAL_PROMPT = "0"
  GIT_SSH_COMMAND = "ssh -o StrictHostKeyChecking=no"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob: https:; img-src 'self' data: blob: https:; connect-src 'self' https:; frame-ancestors 'none';"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  included_files = ["public/**"]

[dev]
  framework = "nextjs"
  targetPort = 3000

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
